### PR TITLE
Notebook introducing the pipeline

### PR DESCRIPTION
**Pull request by matscorse**
An attempt at reviewing the pipeline section of the first IceNet notebook. Originally I had intended for this notebook to be 'tacked' onto the end of the first notebook (that David reviewed) but I think it may be clearer to set this notebook on it's own.

Also an attempt at simplifying the pipeline diagram and making it more readable/accessible just for this notebook.

### CODE REVIEW

**Review by JimCircadian — CHANGES_REQUESTED** [review]
Thanks for this, it's looking good and I especially like the new diagram! Couple of points prior to it going into main, but perhaps the PR could be applied to a working "refactoring" branch that @bnubald can collate all the changes together with. This is just from an initial skim:

* There are a few comments in bold that appear to be outstanding things to add to the notebook?
* The numbering/ordering of the notebooks might want addressing - I'm no longer sure which 01 is the first notebook to look at!
* It occurs to me that this might lead to corresponding changes in the original 01, which aren't in this PR, so not sure if that's somewhere else. 

When we're going into `main` we want these changes to be ready for the public, so might be worth going, as I mentioned, to a feature branch to collect all the changes together from everyone, or to make these small amendments. 

@bnubald are you happy to bring all the changes being worked on together and lead the charge to get them towards main? 

Thanks all!

**Comment by bnubald** [comment]
> Thanks for this, it's looking good and I especially like the new diagram! Couple of points prior to it going into main, but perhaps the PR could be applied to a working "refactoring" branch that @bnubald can collate all the changes together with. This is just from an initial skim:
> 
>     * [ ]  There are a few comments in bold that appear to be outstanding things to add to the notebook?
> 
>     * [ ]  The numbering/ordering of the notebooks might want addressing - I'm no longer sure which 01 is the first notebook to look at!
> 
>     * [ ]  It occurs to me that this might lead to corresponding changes in the original 01, which aren't in this PR, so not sure if that's somewhere else.
> 
> 
> When we're going into `main` we want these changes to be ready for the public, so might be worth going, as I mentioned, to a feature branch to collect all the changes together from everyone, or to make these small amendments.
> 
> @bnubald are you happy to bring all the changes being worked on together and lead the charge to get them towards main?
> 
> Thanks all!

Yes, plan on having a general develop branch (in addition to any feature branches as needed if heavier changes) where PRs will go into before being merged into main if that's ok.

**Comment by bnubald** [comment]
Thanks for this PR @matscorse!

I'll be reviewing this today.

Could the merge branch be changed to the new develop branch I've just made please?

**Comment by bnubald** [comment]
<p>The os module has a symlink method, but I think this is ok since I imagine most pipeline users will end up having to be shell knowledgeable.</p><p> </p><p>I don't think the last line is needed:</p><pre class="ql-syntax" spellcheck="false">cd ../notebook-pipeline
</pre>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/17/discussion/#comment-1961141273'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bnubald** [comment]
<p>I think the first time I ran the pipeline, I coincidentally had the same path to conda as the default, so it just worked :D</p><p> </p><p>But, in subsequent runs, with different conda setup, yes, I did have to update these to my conda install.</p>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/17/discussion/#comment-1961141316'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bnubald** [comment]
<p>Yes, good call, in general, need to expand on the help in this and other pipeline scripts.</p>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/17/discussion/#comment-1961141332'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by matscorse** [comment]
<p>Yeah, I think you are right. That last line isn't needed</p>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/17/discussion/#comment-1961141273'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
