### PR TITLE
Reorganise the first notebook to remove pipeline sections

### PR DESCRIPTION
**Pull request by davidwilby**
**Note**: This is a draft PR for now, would recommend waiting for @matscorse's branch moving the pipeline elements to a separate notebook.

This branch/pr removes the parts of the first notebook that relate to the pipeline, in favour of having that explanation in a separate notebook (to come, I believe @matscorse is working on it).

Happy to be roundly disagreed with on this, so don't pull your punches!

@matscorse and I (hopefully I'm not misrepresenting here!) felt when going through this first notebook that the combined introduction of IceNet as a whole, with the pipeline components of running it (including switching directories/repositories etc) was a bit too challenging for an introductory notebook.

However, I appreciate that the intention here may have been to use the maximum convenience of the pipeline structure to ease the out of the box end-to-end running of IceNet.

My aim here has been to slightly simplify the operations to allow the user to better absorb the steps of running IceNet at the command-line.

Additionally, it is my feeling that the user should be able to run IceNet in its most simple operation by simply pip installing it (`pip install icenet` as in the IceNet readme), which wasn't quite the case here, even though the pipeline shell scripts do introduce extra convenience.

:warning: I recommend enabling rich notebook diffs on GitHub if you don't have it on already. https://github.blog/changelog/2023-03-01-feature-preview-rich-jupyter-notebook-diffs/

### CODE REVIEW

**Comment by JimCircadian** [comment]
Excellent, loving the description on this and looking forward to seeing it! Please do liaise with @bnubald to ensure we keep the eventual porting / sharing of these with the [EDS book in mind](https://edsbook.org), though I think this is undoubtedly going to make the notebooks more appealing. 

Top stuff, thanks all!

**Comment by matscorse** [comment]
If I cant view the changes in GitHub (because GitHub cant render the notebook due to it's size) how can I view this PR?

**Comment by davidwilby** [comment]
> If I cant view the changes in GitHub (because GitHub cant render the notebook due to it's size) how can I view this PR?

If you enable the rich jupyter notebook diffs beta feature (https://github.blog/changelog/2023-03-01-feature-preview-rich-jupyter-notebook-diffs/), GitHub should render a special diff under 'Files Changed'. (tldr: click your user icon top right > Feature Preview >  Rich Jupyter Notebook Diffs > Enable)

**Comment by davidwilby** [comment]
+ `icenet_data_masks` - these are downloaded rather than 'generated' - alter text to suit
+ mention the speed of the help commands
+ training options, maybe include a markdown table to explain all the options
+ predict arguments eg. notebook_data notebook_testrun example_south_forecast - explain what these are and where the directories are! `notebook_data` corresponds to a data loader
+ maybe rename `notebook_` folders.
+ add a md cell before plot output to explain

**Comment by bnubald** [comment]
Thanks a lot for this PR @davidwilby.

I've added [ReviewNB](https://www.reviewnb.com/) for reviewing notebooks in this repo, future notebook PR diffs should be automatically linked to, but for this case:

https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/16/

**Comment by bnubald** [comment]
<p>Good point Matt, the explanation should be extended.</p><p> </p><p>The current relevant sentence is:</p><blockquote>With the second command we&nbsp;<code>-p</code>&nbsp;pickup the output weights from the previous run to continue training.</blockquote><p> </p><p>The first run of <code>icenet_train</code>  trains as one would expect for 10 epochs. The second time it is run with the <code>-p</code> argument, it picks up the weights from the first run and continues along for another 2 epochs (set via <code>-e 2</code> ). So, it has run for effectively 12 epochs.</p><p> </p><p>This can be useful when wanting to continue training runs after having run them previously (If say for example you realised later down the line that you did not run for long enough, or due to resource constraints or any other reason, you had to stop). </p><p> </p>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/16/discussion/#comment-1954617667'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bnubald** [comment]
I'm going through and updating based on discussion topics and expanding in general.

I'm considering creating trees like this that help people understand what is being generated and where.

@davidwilby, @JimCircadian, @matscorse, Thoughts on this? Would this be too much detail for a first/second notebook?

Example for `icenet_data_masks south`:

```
icenet-notebooks/ 
    └── data/masks/south/
        ├──  masks/
        │   ├──  active_grid_cell_mask_01.npy <--- Mask for the active regions to consider for each month (This is for Jan)
        │   ├──  active_grid_cell_mask_02.npy <--- Mask for Feb
        │   ├──  ...
        │   ├──  check.py
        │   ├──  land_mask.npy  <--- This masks the land regions
        │   └──  masks.params   <--- This stores details relating to the "polar hole"
        └──  siconca/           <--- These are temporarily downloaded data used to generate the above masks
            └──  2000/
                ├──  01/
                │   └──  ice_conc_sh_ease2-250_cdr-v2p0_200001021200.nc
                ├──  02/
                │   └──  ice_conc_sh_ease2-250_cdr-v2p0_200002021200.nc
                └── .../
                    └── .../
````

**Comment by matscorse** [comment]
> I'm going through and updating based on discussion topics and expanding in general.
> 
> I'm considering creating trees like this for each of the commands that help people understand what is being generated and where.
> 
> @davidwilby, @JimCircadian, @matscorse, Thoughts on this? Would this be too much detail for a first/second notebook?
> 
> Example for `icenet_data_masks south`:
> 
> ```
> icenet-notebooks/ 
>     └── data/masks/south/
>         ├──  masks/
>         │   ├──  active_grid_cell_mask_01.npy <--- Mask for the active regions to consider for each month (This is for Jan)
>         │   ├──  active_grid_cell_mask_02.npy <--- Mask for Feb
>         │   ├──  ...
>         │   ├──  check.py
>         │   ├──  land_mask.npy  <--- This masks the land regions
>         │   └──  masks.params   <--- This stores details relating to the "polar hole"
>         └──  siconca/           <--- These are temporarily downloaded data used to generate the above masks
>             └──  2000/
>                 ├──  01/
>                 │   └──  ice_conc_sh_ease2-250_cdr-v2p0_200001021200.nc
>                 ├──  02/
>                 │   └──  ice_conc_sh_ease2-250_cdr-v2p0_200002021200.nc
>                 └── .../
>                     └── .../
> ```

I think for me this would have been very useful early on. It's probably going to be a BIG tree so if we did add this to a notebook it would be good if by default the tree would be collapsed (is that even possible in MarkDown?)

**Comment by bnubald** [comment]
> I'm not opposed to that @bnubald but I think we should expedite getting the notebooks refactored only as much as necessary and be careful not to over-produce materials. 😉
> 
> The main thing is getting them out to people via the EDS book. We can add further content later if issues are raised that suggest people haven't understood the content: trying to be proactive on that count isn't the best use of our time!

Understood.

The changes I'm currently making are focused on walking through the usage of IceNet with Louisa and others over the next week or so than the EDS book.

> 
> I think for me this would have been very useful early on. It's probably going to be a BIG tree so if we did add this to a notebook it would be good if by default the tree would be collapsed (is that even possible in MarkDown?)

Yes, have it in a collapsible section currently! (It won't be the full tree, but modified like above to show the patterns and types of outputs - above tree shows just 2 per directory out of the 12 to show the pattern).

I agree on its use early on, I did a lot of `ls` and looking at code to figure out what was happening (still doing so), so thought this would be useful to add for reference, including for myself.

**Comment by davidwilby** [comment]
<p>Good catch if true. Though I'm not sure. The variable passed to the cds api in <code>icenet.data.interfaces.cds.ERA5Downloader</code> is <code>"geopotential"</code> which from the <a href="https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation" target="_blank">ERA5 data docs</a>  is named "Geopotential" with units m^2s^-2.</p>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/16/discussion/#comment-1953103721'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JimCircadian** [comment]
<p>It's geopotential height :) </p>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/16/discussion/#comment-1953103721'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by davidwilby** [comment]
<blockquote>An explanation of the positional arguments, <code>notebook_data</code> , <code>south</code> might be useful? Same in other commands.</blockquote><p> </p><p>Agreed. I'm finding it difficult to come up with an explanation of the first positional argument by digging through the source code. It seems to go into a property called <code>_name</code> for the <code>IcenetPreProcessor</code> class.</p><p> </p><p>Is a simple explanation for the purposes here: "the directory name in which to place the processed data, within the <code>processed</code> directory" or more eloquent words to that effect? Do the <code>icenet_process_*</code> commands create this directory?</p><p> </p><p>Sorry, it's difficult to follow without any documentation for these functions.     </p><p> </p>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/16/discussion/#comment-1953103742'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by bnubald — APPROVED** [review]
🎉

**Comment by bnubald** [comment]
<p>Resolved in later PR.</p><p> </p><p><a href="https://github.com/icenet-ai/icenet-notebooks/pull/19/commits/e6a59aedad6f7707ff73824329148ea81dea67d5" target="_blank">https://github.com/icenet-ai/icenet-notebooks/pull/19/commits/e6a59aedad6f7707ff73824329148ea81dea67d5</a></p>

---

 <a href='https://app.reviewnb.com/icenet-ai/icenet-notebooks/pull/16/discussion/#comment-1953103742'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
